- name: sample print file
  hosts: localhost
  connection: local
  vars:
    url: www.prasaddevops.shop
  tasks:
    - name: print sample file
      ansible.builtin.debug:
        msg: This file is from ansible playbook url - {{url}}



- name: sample print file
  hosts: localhost
  connection: local

  tasks:
    - name: print sample file
      ansible.builtin.debug:
        msg: This file is from ansible playbook url - {{url}}
      vars:
        url: www.prasaddevops.shop
