# dnf install mysql-server -y
# systemctl enable mysqld
# systemctl start mysqld
# mysql_secure_installation --set-root-pass RoboShop@1


- name: Install mysql
  ansible.buildin.dnf:
    name: mysql-server
    state: latest


- name: Start & enable service
  ansible.buildin.systemd_service:
    name: mysql-server
    state: latest
    enabled: yes


- name: Setup Mysql root passwd
ansible.buildin.shell: mysql_secure_installation --set-root-pass RoboShop@1