# app_pre-req() {
#     useradd roboshop
#     mkdir /app
#     curl -L -o /tmp/${component_name}.zip https://roboshop-artifacts.s3.amazonaws.com/${component_name}-v3.zip
#    cd /app
#    rm -rf /app/*
#    unzip /tmp/${component_name}.zip
#     cd /app
# }



- name: Add Application user
  ansible.builtin.user:
    name: roboshop

