#  java() {
#    dnf install maven -y
#    cp ${pwd}/${component_name}.service /etc/systemd/system/${component_name}.service
#    app_pre-req
#    mvn clean package
#    mv target/shipping-1.0.jar shipping.jar
#  }