#  systemd_setup() {
#    cp ${pwd}/${component_name}.service /etc/systemd/system/${component_name}.service
#    systemctl daemon-reload
#    systemctl enable ${component_name}
#    systemctl start ${component_name}
#  }


- name: Copy service file
  ansible.builtin.copy:
    src: /etc/systemd/system/${component_name}.service
    dest: ${pwd}/${component_name}.service


- name: service start
  ansible.builtin.systemd_service:
    name: ${component_name}
    enabled: yes
    daemon_reload: true
